### PR TITLE
fix #452 reevaluate claims if amps > pilot

### LINKED ISSUE #388: Divert mode current set initially set to maximum level regardless of generation
(Bug present in release version but also confirmed present on latest dev build)

My system is configured in "SolarPV-gen" mode with the MQTT topic reflecting generation published to every 10 seconds. Attack/decay are at their defaults.

When divert mode is activated and sufficient generation becomes available (>= 6 Amps), ESP32 Wifi will set the pilot to the maximum charge current regardless of actual generation. It will remain at maximum until either that setting is changed or the generation available would cause the pilot to be set to another integer current level.

Both the "Charge rate" (both main and service tabs) and "Pilot" values in the web GUI reflect what should have been sent to EVSE based on available generation but the actual current is still at the maximum level.

### LINKED ISSUE #452: max_current in claim or override not taken into account if set before starting charge
spotted a bug on claim engine, if you set a claim with max_current set to a lower value than max_current_soft , then when upgrading the claim state to active, it will start the charge with full power ignoring the max_current properties in the claim.
Resending a claim after set state: active will then works.

how to reproduce:
- POST a claim ( over http or mqtt) with {state: "disable"}
- plug the car
- POST a claim with only {max_current: 6}
- POST a claim with {state: "active"}
Charge will start at 32A or what your max_current_soft is set in config instead of 6A
- POST a claim with {max_current: 6}
- now it charges OK at 6A

### LINKED ISSUE #481: Controller restart ignored eco divert mode setting at boot
If OpenEVSE is in Eco (PV Divert) mode and the controller is restarted, those settings are ignored (but are successfully restored) and the car starts charging right away:

**Before restart** 

image

**After restart**

image

As you can see, Eco mode is still active after restarting the controller, but the boot logic ignored it was active and there was no energy being exported at all.

### LINKED ISSUE #513: v4.1.7 Charge starts randomly when in eco mode
Since I updated to v4.1.7 (4 days ago), the charger starts charging itself even when it's on eco mode and there is no sun production.
I've started noticing strange behavior since the current shaper was implemented. In previous versions the shaper woke up the car several times a day, depleted the 12v battery on my Tesla M3 so the car went into failsafe/service request.
I saw it live and the effect was that it was waking the car and proceeding with a micro-charge of 2-3 seconds, then stopped. The car stood awaken. So I disabled the current shaper when I noticed it.

I don't know if its related but now it stays charging.
Yesterday:
Screenshot_20230110_091155_Always starts when connected

Today:
Screenshot_20230111_082739_Starts on it's own with no limit

As you can see, the solar excess topic is supplying negative (consumption) with a max rate of 5s, that it is on eco mode and that when it starts like this, it goes up to the charge limit that is set, in my case 28A.
It only stops charging if the wifi module is rebooted.

This is really bad. Today has done it 4 times, depleted my home battery to 20% (limit), and the last time I only noticed because it caused the inverter overload.

### PR DESCRIPTION
**Pull request by KipK**
Until the bug is corrected on evse fw, this solves the issue and prevent the charge_current going to max when Evse goes from Disabled to Active state ignoring claims & pilot values
fix #452 and should also fix #513 fix #388 fix #481

Edit: It seems those bugs are related to PP_AUTO_AMPACITY beeing set. Posted an issue there: https://github.com/lincomatic/open_evse/issues/156?fbclid=IwAR37MVzzv2WZ7iDPPr3lkryBSUIvsDBsbPJkFu5PcZG1JgMT7e2LF6KxFzQ

So this is not really an OpenEvse bug, but more that OpenEvse and Wifi module don't share the non tethered chargers checking cable ampacity state and we have confusions here.

### CODE REVIEW

File: src/main.cpp [hunk 1]
```diff
@@ -198,6 +199,23 @@ loop() {
...
+          DBUGVAR(current);
+          DBUGVAR(pilot);
+          evse.evaluateClaims();
+          MicroTask.wakeTask(evse);
+          
+        }
+        Timer4 = millis();
+      }
+  
+
```
Comment (jeremypoulter) [inline src/main.cpp:218]: This really should be hidden away in the EVSE manager/monitor if it is really needed, however getAmps just gets a cached value, so I think ou just need to tag this code into getChargeCurrentAndVoltageFromEvse() which is regularly called

**Comment by jeremypoulter** [comment]
Actually I don't think getAmps is what you should be checking against, that is the live amp reading. What may be an idea is calling openevse.getCurrentCapacity after a state change/current change then doing the check to see if the pilot on the EVSE is the same as what the Monitor thinks it should be, so somewhere here, https://github.com/OpenEVSE/ESP32_WiFi_V4.x/blob/master/src/evse_monitor.cpp#L478, and here, https://github.com/OpenEVSE/ESP32_WiFi_V4.x/blob/master/src/evse_monitor.cpp#L280

**Comment by KipK** [comment]
Do you think then we should reevaluate claim or just set the pilot to evse ?

**Comment by jeremypoulter** [comment]
I think just setting the pilot should be sufficient

**Comment by KipK** [comment]
I have rewrote it on getChargeCurrentAndVoltageFromEvse()

Can't make the change using openevse.getCurrentCapacity , i'm lost with those callbacks.
But it works good as it, ( still the 2-3 sec glitch )

**Comment by KipK** [comment]
Ok I got it thanks. 
I've made the change, gotta test first.

**Comment by KipK** [comment]
Jiust tested but it doesn't work now. Amps stays at 32

**Comment by KipK** [comment]
I have added some debug:

#####   CHECK BUG #452    #####
pilot = 32
getPilot() = 6
####  Pilot differents set again

So the check works ok, but setCurrentCapacity seems to not have effect here.

**Comment by KipK** [comment]
Ok it works now. I've rebased the commits in one.

**Comment by KipK** [comment]
After few tests, I can say it reacts faster than the claim approach I did first. I don't see spikes over the set limit and it stabilise quiet fast.

Until we got a proper integration of auto_ampacity between openevse fw and ESP32 one, this should fit.

File: src/evse_monitor.cpp [hunk 2]
```diff
@@ -359,6 +375,10 @@ unsigned long EvseMonitor::loop(MicroTasks::WakeReason reason)
     getEnergyFromEvse();
   }
 
+  // Check if pilot is wrong ( solve OpenEvse fw compiled with -D PP_AUTO_AMPACITY)
+  if (isCharging())
+    verifyPilot();
```
Comment (jeremypoulter) [inline src/evse_monitor.cpp:380]:
```suggestion
  if (isCharging()) {
    verifyPilot();
  }
```

File: src/evse_monitor.cpp [hunk 3]
```diff
@@ -464,7 +484,7 @@ void EvseMonitor::setPilot(long amps, std::function<void(int ret)> callback)
     amps = _min_current;
   }
 
-  if(amps == _pilot)
+  if(amps == _pilot && !_pilot_is_wrong)
```
Comment (jeremypoulter) [inline src/evse_monitor.cpp:487]: Think it would be cleaner to add a parameter to the method with a default value, eg `bool force = false`

File: src/evse_monitor.cpp [hunk 4]
```diff
@@ -311,6 +312,22 @@ void EvseMonitor::updateEvseState(uint8_t evse_state, uint8_t pilot_state, uint3
   }
 }
 
+void EvseMonitor::verifyPilot() {
+    // After some state changes the OpenEVSE module compiled with PP_AUTO_AMPACITY will reset to the maximum pilot level, so reset to what we expect
+    _openevse.getCurrentCapacity([this](int ret, long min_current, long max_hardware_current, long pilot, long max_configured_current)
+    {
+      if(RAPI_RESPONSE_OK == ret && pilot != getPilot())
```
Comment (jeremypoulter) [inline src/evse_monitor.cpp:319]: May need to just check for larger pilot values to handle case where EVSE has loimited the current to a lower value than set.
```suggestion
      if(RAPI_RESPONSE_OK == ret && pilot > getPilot())
```

File: src/evse_monitor.cpp [hunk 5]
```diff
@@ -311,6 +312,22 @@ void EvseMonitor::updateEvseState(uint8_t evse_state, uint8_t pilot_state, uint3
...
+      {
+        DBUGLN("####  Pilot is wrong set again");
+        DBUGVAR(pilot);
+        DBUGVAR(getPilot());
+        _pilot_is_wrong = true;
+        setPilot(getPilot());
+        _pilot_is_wrong = false;
```
Comment (jeremypoulter) [inline src/evse_monitor.cpp:326]: See other comments but should be something like this

```suggestion
        setPilot(getPilot(), true);
```

File: src/evse_monitor.cpp (hunk 4 above)
Comment (KipK) [reply src/evse_monitor.cpp]: yes probably better. Change made

File: src/evse_monitor.cpp (hunk 3 above)
Comment (KipK) [reply src/evse_monitor.cpp]: ok I've added the param to setPilot

**Review by jeremypoulter — APPROVED** [review]
